### ISSUE TITLE
Problem when install on Win7 64bit

### ISSUE THREAD

**Issue by leeooox** [jpoirier/visa#1]
My OS is Win7 64bit.

when I run "go get github.com/jpoirier/visa"  it show some errors:

# github.com/jpoirier/visa
src\github.com\jpoirier\visa\defs.go:5:18: fatal error: visa.h: No such file or directory compilation terminated.

**Comment by jpoirier** [comment]
Unfortunately building the package on Windows requires you to copy and
paste the visa.h header file. You'll need find the visa.h file (it will be
somewhere in the Visa library installation folder) and copy it to the visa
package's folder (YOUR_GOPATH/github.com/jpoirier/visa), alternatively you
can set the header file path in visa.go, line 44.

To download the package without building it use:

```
go get -d github.com/jpoirier/visa
```

To build the package after downloading it, and assuming you've copied the
header file to the visa package's folder:

```
go build github.com/jpoirier/visa
```

Apologies for the inconvenience.

**Comment by leeooox** [comment]
I followed the instruction:
1. go get -d github.com/jpoirier/visa
2. "visa.h" and "visatype.h" to the visa package folder
3. go build github.com/jpoirier/visa 
but still found errors as below, which version of MinGW should I use?

could not determine kind of name for C.VI_ASRL_WIRE_232_AUTO
could not determine kind of name for C.VI_ASRL_WIRE_232_DCE
could not determine kind of name for C.VI_ASRL_WIRE_232_DTE
could not determine kind of name for C.VI_ASRL_WIRE_485_2_AUTO
could not determine kind of name for C.VI_ASRL_WIRE_485_2_DTR_CT
could not determine kind of name for C.VI_ASRL_WIRE_485_2_DTR_EC
could not determine kind of name for C.VI_ASRL_WIRE_485_4
could not determine kind of name for C.VI_ATTR_ASRL_ALLOW_TRANSM
could not determine kind of name for C.VI_ATTR_ASRL_BREAK_LEN
could not determine kind of name for C.VI_ATTR_ASRL_BREAK_STATE
could not determine kind of name for C.VI_ATTR_ASRL_CONNECTED
could not determine kind of name for C.VI_ATTR_ASRL_DISCARD_NULL
could not determine kind of name for C.VI_ATTR_ASRL_WIRE_MODE
could not determine kind of name for C.VI_ATTR_SYNC_MXI_ALLOW_EN
could not determine kind of name for C.VI_ATTR_VXI_DEV_CMD_TYPE
could not determine kind of name for C.VI_ATTR_VXI_DEV_CMD_VALUE
could not determine kind of name for C.VI_ATTR_VXI_TRIG_DIR
could not determine kind of name for C.VI_ATTR_VXI_TRIG_LINES_EN
could not determine kind of name for C.VI_DEREF_ADDR_BYTE_SWAP
could not determine kind of name for C.VI_ERROR_LINE_NRESERVED
could not determine kind of name for C.VI_ERROR_MACHINE_NAVAIL
could not determine kind of name for C.VI_ERROR_QUEUE_OVERFLOW
could not determine kind of name for C.VI_EVENT_ASRL_BREAK
could not determine kind of name for C.VI_EVENT_ASRL_CHAR
could not determine kind of name for C.VI_EVENT_ASRL_CTS
could not determine kind of name for C.VI_EVENT_ASRL_DCD
could not determine kind of name for C.VI_EVENT_ASRL_DSR
could not determine kind of name for C.VI_EVENT_ASRL_RI
could not determine kind of name for C.VI_EVENT_ASRL_TERMCHAR
could not determine kind of name for C.VI_EVENT_VXI_DEV_CMD
could not determine kind of name for C.VI_INTF_FIREWIRE
could not determine kind of name for C.VI_INTF_RIO
could not determine kind of name for C.VI_PXI_LBUS_NONE
could not determine kind of name for C.VI_PXI_LBUS_UNKNOWN
could not determine kind of name for C.VI_VXI_DEV_CMD_TYPE_16
could not determine kind of name for C.VI_VXI_DEV_CMD_TYPE_32
could not determine kind of name for C.VI_VXI_RESP_NONE
could not determine kind of name for C.VI_VXI_RESP_PROT_ERROR

**Comment by jpoirier** [comment]
Those are VISA definitions and they should be in visa.h (not sure why Go is
complaining) but I'd also forgotten about visa.h including visatype.h and
vpptype.h so you'll need to set the include path in visa.go instead,

e.g. change at line number 44 change:

```
#cgo CFLAGS: -I.
```

to the path where the header files are, use forward slashes for folder
separators and backslashes for spaces

```
#cgo CFLAGS: -Ic:/Program\ Files/NI/header_files
```

or use quotes:

```
#cgo CFLAGS: -I"c:/Program Files/NI/header_files"
```

It has been a while since I've compiled the package on Windows and I'll do
a compile on my side tomorrow (Texas time)

**Comment by leeooox** [comment]
I found that visa.h have many different distributions, some have VI_ASRL_WIRE_232_AUTO, but some not. 

eg. this code https://github.com/rbmj/wpilib/blob/master/visa/visa.h have VI_ASRL_WIRE_232_AUTO, but it lack of other defines like VI_ATTR_PXI_ALLOW_WRITE_COMBINE.

The visa.h on my PC is aslo different from the above link.

**Here is my work around:**
Remove the in defs.go and add lib link, the build is successful.

D:/clibs/visa/lib is visa64.lib folder
D:/clibs/visa/include is header files folder

#cgo amd64 linux LDFLAGS: -LD:/clibs/visa/lib -lvisa64
#cgo darwin LDFLAGS: -framework VISA
#cgo windows LDFLAGS: -LD:/clibs/visa/lib -lvisa64
#cgo 386 linux LDFLAGS: -lvisa
#cgo 386 darwin LDFLAGS: -framework VISA
#cgo 386 windows LDFLAGS: -LD:/clibs/visa/lib -lvisa64
#cgo CFLAGS: -ID:/clibs/visa/include

**Run the example**
When I play with FindRsrc.go, the build is also without errors, but after run, it shows erros as below.

Exception 0xc0000005 0x0 0xffffffffffffffff 0x5c5cc8
PC=0x5c5cc8
signal arrived during external code execution

github.com/jpoirier/visa._Cfunc_viOpenDefaultRM(0xc0820042b4, 0xc000000000)
    github.com/jpoirier/visa/_obj/_cgo_gotypes.go:1244 +0x44
github.com/jpoirier/visa.OpenDefaultRM(0x0)
    D:/mygo/src/github.com/jpoirier/visa/visa.go:97 +0x45
main.main()
    D:/mygo/src/visa_test/FindRsrc.go:35 +0x53

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    c:/go/src/runtime/asm_amd64.s:1998 +0x1
rax     0xc08202ffb0
rbx     0xc08202fe10
rcx     0xc0820042b4
rdi     0xc08202fe10
rsi     0xc08202ffb0
rbp     0x0
rsp     0x22fd88
r8      0xc08201a000
r9      0xc08202fda0
r10     0x5034c0
r11     0x710158
r12     0x10
r13     0x561124
r14     0x3
r15     0x8
rip     0x5c5cc8
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

**Comment by jpoirier** [comment]
Unfortunately I've not used, nor updated, the package in a couple of years
but I'll work on syncing it with the latest NI Visa library next week, and
pull requests are welcome.

Not sure what's causing the error but what version of Go are you using?

btw, thanks for taking the time to report back the problems you've
encountered!

**Comment by jpoirier** [comment]
I was able to run the FindRsrc example using the following steps:

```
- installed Go 1.7rc6 
- install the latest NI Visa tools, version 16
- install a 64 bit GCC via http://tdm-gcc.tdragon.net/download, add C:\TDM-GCC-64\bin to PATH
- go get -d github.com/jpoirier/visa
- copy visa.h, visatype.h, vpptype.h from C:/Program Files/National Instruments/shared/CompilerSupport/c/Include to %GOPATH%/src/github.com/jpoirier/visa
- copy visa64.dll from C:/Windows/System32 to C:/Temp
- edit visa.go, change: #cgo windows LDFLAGS: -lvisa  to: #cgo windows LDFLAGS: -lvisa -LC:/Temp
- open a Window's shell in %GOPATH%/src/github.com/jpoirier/visa
- run: go build -o %GOPATH%/pkg/windows_amd64/github.com/jpoirier/visa.a visa.go exports.go defs.go
- from the shell window cd to visa/examples and: go run FindRsrc.go
```

Notes:

```
- it seems there are permission issues when setting cgo paths to C:/Windows and/or C:/Program Files, etc...
- cgo is looking for visa64.dll and it's cgo include path can't be relative   
```
